### ISSUE TITLE
[Module Proposal]: AVD Management Plane Resources

### ISSUE THREAD

**Issue by moisesjgomez** [Azure/Azure-Verified-Modules#65] opened 2023-09-13 21:10 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm-ptn-desktopvirtualization-logicalresources

### Module Details

Module would deploy management plane resources for AVD (Workspace, application group, host pool, scaling plan)

For reference: 
https://github.com/Azure/avdaccelerator/blob/main/workload/bicep/modules/avdManagementPlane/deploy.bicep

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

moisesjgomez

**Comment by jtracey93** [comment] 2023-09-13 21:28
Hi @moisesjgomez,

Thanks for the proposal. 

I think this should actually be a pattern module instead of a resource module, as per the classification definitions here: https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/

Could you please amend the module proposal and module name if you agree and we will triage further 👍

**Comment by moisesjgomez** [comment] 2023-09-13 21:37
@jtracey93 I've updated the proposal and module name. Let me know if there's anything else I can do. Thank you.

**Comment by jtracey93** [comment] 2023-09-14 08:28
cc: @danycontre for awareness on this submission as he owns the AVD LZA, is this planned work for the AVD LZA team and therefore aligned?

**Comment by jtracey93** [comment] 2023-09-28 18:22
@jeanchg or @matebarabas can we validate the module names and if we have a current owner of the CARML equivalent, if it exists?

If not lets send the confirmation to @moisesjgomez to confirm ownership statement 👍

**Comment by matebarabas** [comment] 2023-09-29 03:14
@moisesjgomez, I'll follow up with you here: https://github.com/Azure/Azure-Verified-Modules/issues/66

**Comment by matebarabas** [comment] 2023-10-03 01:28
Duplicate of #150.

**Closed by matebarabas** 2023-10-03 01:28 UTC
Labels: Needs: Attention :wave:, Needs: Triage :mag:, Status: No Recent Activity :zzz:, Type: Duplicate :palms_up_together:, Type: New Module Proposal :bulb:, Language: Bicep :muscle:

**Comment by danycontre** [comment] 2023-10-03 13:24
@matebarabas agree, this item needed to be closed as new ones were submitted.
