### ISSUE TITLE
[Module Proposal]: `avm/res/web/connection`

### ISSUE THREAD

**Issue by krbar** [Azure/Azure-Verified-Modules#680] opened 2024-02-22 15:08 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/web/connection

### Module Details

Migration from CARML

### Do you want to be the owner of this module?

No

**Comment by matebarabas** [comment] 2024-02-22 23:04
@krbar, this is a duplicate of https://github.com/Azure/Azure-Verified-Modules/issues/566 that @segraef is already working on. I'll close this issue. Please check with Sebastian if you can help with anything. Thanks!

#wontfix

**Closed by matebarabas** 2024-02-22 23:04 UTC
Labels: Needs: Triage :mag:, Type: Duplicate :palms_up_together:, Type: New Module Proposal :bulb:, Language: Bicep :muscle:, Needs: Module Owner :mega:
