### ISSUE TITLE
[Module Proposal]: `avm-ptn-aks-production`(tf)

### ISSUE THREAD

**Issue by zioproto** [Azure/Azure-Verified-Modules#518] opened 2024-01-12 08:22 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

I'm not sure, please advise

### Module Name

avm-ptn-aks-production

### Module Details

This is the original comprehensive AKS Verified Module, including 100+ properties and giving users the freedom to configurate their files with their exact specifications: https://github.com/Azure/terraform-azurerm-aks. These configuration options are incredibly comprehensive, encompassing every facet of AKS configuration. However, this design may pose challenges for individuals who prefer streamlined options or lack extensive AKS background knowledge. To ensure seamless experience for all users and to keep pace with the growing AKS Azure user base, we want to launch several simplified versions of the AKS module. These streamlined versions will feature default settings for certain complex configurations, mirroring the user-friendly design in the Azure Portal.
 
We will categorize the AKS modules based on the cluster preset configuration settings. This approach is essential as modules are significantly impacted by these configurations, influencing resource allocation, scalability, cost, compatibility, networking, security, and various other aspects. 
 
The first simplified AKS module we want to release is the production standard module. (Simpler than the original comprehensive AKS module, but still suitable for most business scenarios). 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

zioproto

### (Optional) Secondary Module Owner's GitHub Username (handle)

Jingwei-MS

**Comment by mbilalamjad** [comment] 2024-01-25 01:31
[Referencing](https://github.com/Azure/Azure-Verified-Modules/issues/46) a similar module proposal on which @jchancellor-ms is working

@matt-FFFFFF, @lonegunmanb interested in your feedback based on the equivalent TFVM module for AKS how we should handle these two module proposals

**Comment by nellyk** [comment] 2024-01-25 17:15
@mbilalamjad  To add to our initial description as per our discussion in the office hours we are going ahead with with creating a pattern module which will have the above setup for AKS + ACR. 

Would it be possible to help us with the naming for the pattern module?

**Comment by mbilalamjad** [comment] 2024-02-06 07:25
Hi @zioproto,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by mbilalamjad** [comment] 2024-02-06 07:27
> @mbilalamjad Bilal Amjad FTE To add to our initial description as per our discussion in the office hours we are going ahead with with creating a pattern module which will have the above setup for AKS + ACR.
> 
> Would it be possible to help us with the naming for the pattern module?

@nellyk had a discussion with the team and updated the name to suggested, let me know if that makes sense

**Comment by zioproto** [comment] 2024-02-06 08:35
"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

**Comment by mbilalamjad** [comment] 2024-02-06 09:00
Hi @zioproto,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- You must be the owner of the GitHub teams as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
- Please check that your name has been updated in the module index page (this should happen shortly after you confirmed ownership).

You can now take ownership of this module and start improving it as needed! ✅ Happy coding! 🎉

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by mbilalamjad** [comment] 2024-03-05 07:02
Requested @zioproto to share an update here.

**Comment by zioproto** [comment] 2024-03-05 07:09
The module is currently in development:

@nellyk is actively working on these  3 PRs:
* https://github.com/Azure/avm-ptn-aks-production/pull/9
* https://github.com/Azure/avm-ptn-aks-production/pull/10
* https://github.com/Azure/avm-ptn-aks-production/pull/12

@nellyk do you agree after those 3 are merged we could release a first preview version ? Thanks

**Comment by nellyk** [comment] 2024-03-15 14:39
@mbilalamjad 
Wanted to provide an update 

@zioproto made changes and the above have been merged. We have a pending item with the network configuration since we would like users to supply a VNet that requires a subnet for the natgateway and a natgateway to be created. We are exploring options for this so that it is less complicated for users

**Comment by nellyk** [comment] 2024-04-19 09:13
@mbilalamjad  i think we can close this now as the module has been released https://registry.terraform.io/modules/Azure/avm-ptn-aks-production/azurerm/latest

**Comment by mbilalamjad** [comment] 2024-04-24 06:27
Thank you so much @nellyk & @zioproto for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-ptn-aks-production/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production

**Closed by mbilalamjad** 2024-04-24 06:27 UTC
Labels: Needs: Attention :wave:, Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Terraform :globe_with_meridians:, Class: Pattern Module :package:
