### ISSUE TITLE
[Module Proposal]: `avm/ptn/network/hub-networking`

### ISSUE THREAD

**Issue by hundredacres** [Azure/Azure-Verified-Modules#604] opened 2024-02-03 00:19 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Bicep

### Module Classification?

Pattern Module

### Module Name

avm/ptn/network/hub-networking

### Module Details

Hub-spoke network topology in Azure, following Azure Reference Architecture best practices, as shown [here](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli).

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

hundredacres

**Comment by matebarabas** [comment] 2024-02-03 01:40
@hundredacres, thank you for proposing this module! As this is categorized as a pattern module, its approval will require a more thorough assessment. The AVM core team will get back to you soon. Thank you for your patience!

**Comment by matebarabas** [comment] 2024-02-08 19:42
@hundredacres, thank you for your patience! The core team took a look at this proposal and agrees that it would be great to have this pattern module and would like to proceed with this. 

Before approving, we'd like to ask what resources do you see to be added to this pattern? This is important, since the AAC pattern you linked seems pretty broad (with VMs in multiple subnets, etc.), and we'd like to clarify where this solution would start & end. 

Also, this specific example seems to use a VPN GW, whereas the hub & spoke concept also applies for ER scenarios, etc. Do you plan to cater for those other scenarios too, or would this be strictly the one for VPN connection? Based on your answer, we'll need to work on the module's name a bit too, as we'd need to cater for additional hub & spoke scenarios.
Thanks!

CC: @jtracey93

**Comment by hundredacres** [comment] 2024-02-08 22:45
Resources would be:
- Microsoft.Network/bastionHosts
- Microsoft.Network/azureFirewalls
- Microsoft.Network/virtualnetworks
- Microsoft.Network/virtualnetworks/subnets
- Microsoft.Network/routeTables
- Microsoft.Network/routeTables/routes
- Microsoft.Network/publicIPAddresses
- Microsoft.Network/virtualNetworkGateways
- Microsoft.Network/connections
- Microsoft.Network/expressRouteCircuits
- Microsoft.Network/expressRouteCircuits/authorizations

The solution will deploy a hub, which will consist of a virtualnetwork, some subnets, a firewall and bastion host. It will also deploy 2 spokes, each with a virtualnetwork, some subnets and nsg's. I didn't want to make the initial pattern too complex.

I was thinking of starting with an ER scenario, since it's something we use internally.

**Comment by matebarabas** [comment] 2024-02-08 23:14
Thanks, @hundredacres, for clarifying! This sounds good to me. We can double click on the details later (even in next versions), but just out of curiosity, are you planning to build this in a way that allows consumers to scale the number of spoke VNETs, and the subnets within those? (My next question will be multi-geo deployment for the same, but I'll keep it for vNext. 🙂)

@jtracey93, any comments/additional questions on your end? Regarding the name, what I think we'll need to consider is the following:
- Can this be called a Landing Zone or Landing Zone Accelerator (or are these terms retained for workload-related patterns only that this solution wouldn't meet the criteria of)?
- As it will specifically come with an ER, and uses VNET peering (not a vWAN), I think we should reflect these details in the name, so how about something like `avm/ptn/network-lza/hub-spoke-peer-w-er` or if we want to be even more specific `avm/ptn/network-lza/hub-spoke-peer-w-azfw-bastion-er` ?

**Comment by matebarabas** [comment] 2024-02-14 01:23
@chrisking81, please don't commence development of this module yet and don't change the status of this issue as the approval process hasn't fully concluded yet. Thank you for your patience!

**Comment by chrisking81** [comment] 2024-02-14 07:43
Apologies @matebarabas this was done accidentally when reading through the Github Project on my iPad. Hadn't even noticed that I had done this

**Comment by jtracey93** [comment] 2024-02-14 11:28
Hey @hundredacres & @matebarabas,

Thanks for the conversation here.

My inputs are:

- I think we should not deploy spokes as we see customers dont often manage all their networking across their estate in one module
- We should focus this module purely on the Hub aspect, and provide an example on how to use it to peer to spokes etc using the VNET resource module etc.
- This would align with the incoming Terraform AVM Pattern module of https://github.com/Azure/terraform-azurerm-hubnetworking (migration from TFVM owned by our very own @matt-FFFFFF)
    - Current features of this module:
        - This module will deploy `n` number of virtual networks and subnets. Optionally, these virtual networks can be peered in a mesh topology.
        - A routing address space can be specified for each hub network, this module will then create route tables for the other hub networks and associate them with the subnets.
        - Azure Firewall can be deployed in each hub network. This module will configure routing for the AzureFirewallSubnet.
    - But I love the idea of including Gateways, Bastion etc., all the resources you'd need in a Hub/Connectivity subscription - aligning to ALZ
        - If we can do this, we can look at using this module as part of ALZ Bicep when we get around to migrating it to be built on AVM and if this module provides the same capabilities as our existing ALZ Bicep module that would be amazing https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/hubNetworking - cc: @oZakari 

> We should **NOT** include AVNM in this module right now, as that changes the way you would deploy and managed VNETs all up in your estate completely 

As for name, how about `avm/ptn/network/traditional-hub` as this is how its referred to in ALZ https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology

Thoughts?

**Comment by matebarabas** [comment] 2024-02-14 22:14
Thanks for your detailed response @jtracey93! I agree to your points. I've changed the name of the module accordingly.

@hundredacres, once you confirmed you agree to the things explained above, we can continue with the "handshake" process, and then you can start the development. Thanks!

**Comment by matt-FFFFFF** [comment] 2024-02-14 23:20
Could I suggest hubnetworking instead of traditional-hub? This makes it similar to the TF one. Also the current suggested means it is not clear that this module pertains to networking at all.

The TF one deploys a multi- hub network and configured routing.

The additional vnet gateway module can then be added on top, this providing almost an exact replica of the functionality described here.

**Comment by hundredacres** [comment] 2024-02-15 00:13
I was going to attempt to model the Bicep version after the TF version, so there's consistency in the patterns across the 2 languages and I'm fine with either suggested name.

**Comment by hundredacres** [comment] 2024-02-15 00:43
Will remove the spokes from the pattern and focus on the hub specifically. Are we ok with having Bastion be an optional add-on? Or would we have an example showing that?

**Comment by jtracey93** [comment] 2024-02-15 08:24
I'm happy to say `hubnetworking` if it makes or TFVM module migration easier @matt-FFFFFF 

As for adding bastion etc into this module @hundredacres im more than okay with this, I also think you could add private dns zones as well - FYI we are working on another pattern module for these that you may want to add in when it available; it'll create all the private link dns zones that are required and link to a vent etc.

**Comment by matebarabas** [comment] 2024-02-15 21:33
@jtracey93, @matt-FFFFFF, as we discussed internally, I've renamed this module to `avm/ptn/network/hub-networking` so that it's aligned with its Terraform equivalent. 

It appears there's also an agreement regarding this module's content, so let's proceed with the handshake process! 😉

**Comment by matebarabas** [comment] 2024-02-15 21:33
Hi @hundredacres,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

**Comment by hundredacres** [comment] 2024-02-15 23:05
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by matebarabas** [comment] 2024-02-15 23:06
Hi @hundredacres,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

Before starting development, please ensure ALL the following requirements are met.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - for naming your module
  - `TelemetryIdPrefix` - for your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repo name and folder path are defined in `RepoURL`
  - Create GitHub teams for module owners and contributors and grant them permissions as outlined [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
  - Grant permissions for the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

Check if this module exists in the other IaC language. If so, collaborate with the other owner for consistency. 👍

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published! Please include a link pointing to your PR, once available. 🙏**

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

**Comment by matebarabas** [comment] 2024-03-08 01:54
@hundredacres, can you please provide any updates on this module? Thank you!

**Comment by matebarabas** [comment] 2024-03-11 19:15
No worries, thank you for the update! Please provide a link to the PR when available! Thanks!

**Comment by matebarabas** [comment] 2024-03-18 19:34
@hundredacres, please don't forget to provide a link to the PR when available. Thank you!

**Comment by hundredacres** [comment] 2024-03-19 18:03
Draft PR is here: https://github.com/Azure/bicep-registry-modules/pull/1257

Close to flipping it open for review, pending resolution of https://github.com/Azure/bicep-registry-modules/issues/1315

**Comment by matebarabas** [comment] 2024-09-05 22:29
@hundredacres, I can see that the [prerequisite](https://github.com/Azure/bicep-registry-modules/issues/1315) was merged in March, and that you've recently updated [your PR](https://github.com/Azure/bicep-registry-modules/pull/1257) that is now live. Do you think you can work on any items identified in the review, so that we can close this sometime soon? Thank you!

**Comment by hundredacres** [comment] 2024-09-27 01:41
PR was merged

**Closed** 2024-09-27 01:41 UTC
Labels: Needs: Attention :wave:, Status: In PR :point_right:, Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Bicep :muscle:, Class: Pattern Module :package:

**Comment by matebarabas** [comment] 2024-09-27 02:09
- [x] Module published.
- [x] GitHub teams are available and assigned to their parents.
- [x] `CODEOWNERS` file updated.
- [x] Issue template file updated.
 
Thank you for your work @hundredacres!
