### ISSUE TITLE
[Orphaned Module]: ADF is orphaned

### ISSUE THREAD

**Issue by clintgrove** [Azure/Azure-Verified-Modules#597] opened 2024-02-01 15:51 UTC
### Bicep or Terraform?

Bicep

### Module Classification?

Resource Module

### Module Name

avm/res/databricks/workspace

### Module Details

I can take ownership of this. I have experience doing bicep ADF deployment

### Do you want to be the new owner of this module?

Yes

### Module Owner's GitHub Username (handle)

clintgrove

**Comment by matebarabas** [comment] 2024-02-02 00:21
@clintgrove, thank you for volunteering to help with this module! This is a duplicate of https://github.com/Azure/Azure-Verified-Modules/issues/431 - can you please leave a comment on this one @mentioning me? Thank you!

I'm going to close this one now. #wontfix

**Closed by matebarabas** 2024-02-02 00:21 UTC
Labels: Needs: Triage :mag:, Type: Duplicate :palms_up_together:, Status: Module Orphaned :eyes:, Language: Bicep :muscle:, Needs: Module Owner :mega:, Status: In Triage :mag:
