### ISSUE TITLE
[Module Proposal]: AVD Firewall Policy (tf)

### ISSUE THREAD

**Issue by cshea15** [Azure/Azure-Verified-Modules#154] opened 2023-10-02 20:47 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Check this module doesn't already exist in another project that is being evolved into AVM

- [X] I have checked for that this module doesn't already exist in CARML or TFVM

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

avm-res-network-firewallpolicy

### Module Details

creating an azure firewall policy that is specific for AVD network rules outbound from the required URL list. 

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username

cshea15

**Comment by jtracey93** [comment] 2023-10-03 05:47
Hey @cshea15 

This would be a pattern module, if anything in my opinion as it's providing specificity to a single architecture pattern. 

Would it also just be a policy? Could this be wrapped together with other resource modules to help accelerate more than just the firewall policy?

Otherwise this would be a duplicate of #153 and the AVD rules could just be an example in the `tests/e2e` folder. 

Let us know your thoughts on direction here. 

Thanks

Jack

**Comment by jtracey93** [comment] 2023-10-03 12:25
Awesome thanks @cshea15 

Let's close this one and add as an example for #153 and to the pattern in the future

**Closed** 2023-10-03 12:25 UTC
Labels: Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Terraform :globe_with_meridians:, Status: Won't Fix :broken_heart:
