### ISSUE TITLE
[Module Proposal]: REPLACE ME WITH MODULE BEING PROPOSED

### ISSUE THREAD

**Issue by Misba-Yousuf** [Azure/Azure-Verified-Modules#327] opened 2023-11-22 09:50 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

TF: avm/res/network/private-endpoint

### Module Details

Terraform Module for private-endpoint.

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

Misba-Yousuf

### (Optional) Secondary Module Owner's GitHub Username (handle)

miyousuf

**Comment by mbilalamjad** [comment] 2023-11-22 15:58
@Misba-Yousuf closing as duplicate of https://github.com/Azure/Azure-Verified-Modules/issues/328

**Closed by mbilalamjad** 2023-11-22 15:58 UTC
Labels: Needs: Triage :mag:, Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Terraform :globe_with_meridians:
