### ISSUE TITLE
[Module Proposal]: `avm-res-compute-virtualmachine` (tf)

### ISSUE THREAD

**Issue by PmeshramPM** [Azure/Azure-Verified-Modules#42] opened 2023-09-05 10:59 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals

### Terraform or Bicep?

Terraform

### Module Classification?

Resource Module

### Module Name

Module Name -> avm-res-compute-virtualmachine
GH repo name ->terraform-azurerm-avm-res-compute-virtualmachine

### Module Details

Evolving the existing Terraform module from TFVM - https://github.com/Azure/terraform-azurerm-virtual-machine

### Do you want to be the owner of this module?

No

**Comment by prasad3017** [comment] 2023-09-08 18:04
hello @jtracey93  @PankajMeshramCSA  this is something I will be working with Donovan. I am trying to get his git handle to assign it to him. 

for now ,putting it on my name.

**Comment by prasad3017** [comment] 2023-09-08 18:05
@jtracey93  @PankajMeshramCSA  I cant assign the task myself. do you know why ?

**Comment by jtracey93** [comment] 2023-09-08 18:06
You do not have permissions on this repo, which is correct. 

Are you going to own this module for its lifetime as per the AVM specs and do the module development work?

**Comment by prasad3017** [comment] 2023-09-08 19:33
Assignment permission is blocked? Is there a repository I need to part of ?

To your question: That's the plan. This is something I will be working Donnovan. He will lead but he is OOF today.



Thanks
Prasad G

**Comment by jtracey93** [comment] 2023-09-08 19:48
@prasad3017 Yes only the core team can assign issues/proposals to folks, this is by design so we can control people duplicating efforts and we ensure that owners understand their responsibilities. 

This is the same in all open source projects, folks outside of the maintainer/core teams have no permissions on the repo to triage issues or merge code. 

Once you have synced with Donovan please provide both your GitHub aliases/usernames below and confirm you agree to the below:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions/
- https://azure.github.io/Azure-Verified-Modules/specs/shared/
- https://azure.github.io/Azure-Verified-Modules/help-support/module-support/

Also looping in @matt-FFFFFF here and @lonegunmanb as there are existing TFVM modules that may be converted or used as a starting point for this AVM module:

- https://github.com/Azure/terraform-azurerm-compute/blob/master/README.md
- https://github.com/Azure/terraform-azurerm-virtual-machine/blob/main/README.md

**Comment by jeanchg** [comment] 2023-09-11 09:50
Assigning @jchancellor-ms as discussed

**Comment by PmeshramPM** [comment] 2023-09-28 12:55
@jchancellor-ms - Please pay attention to the module name and GH repo name above. I have updated that based on specs

**Comment by mbilalamjad** [comment] 2023-11-18 05:05
@jchancellor-ms based off our conversation on confidential compute, just sharing the below for context
https://github.com/Azure/Azure-Verified-Modules/issues/39

**Comment by mbilalamjad** [comment] 2023-11-30 00:12
Thank you so much @jchancellor-ms for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-compute-virtualmachine/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine

**Closed by mbilalamjad** 2023-11-30 00:12 UTC
Labels: Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Terraform :globe_with_meridians:, Status: Module Available :green_circle:, Class: Resource Module :package:
