### ISSUE TITLE
[Module Proposal]: `avm-res-compute-virtualmachinescaleset` (tf)

### ISSUE THREAD

**Issue by terrymandin** [Azure/Azure-Verified-Modules#265] opened 2023-11-03 15:39 UTC
### Check for previous/existing GitHub issues/module proposals

- [X] I have checked for previous/existing GitHub issues/module proposals.

### Check this module doesn't already exist in the module indexes

- [X] I have checked for that this module doesn't already exist in the module indexes; or I'm proposing the module to be migrated from CARML/TFVM.

### Bicep or Terraform?

Terraform

### Module Classification?

Resource Module

### Module Name

terraform-azurerm-avm-res-compute-virtualmachinescaleset

### Module Details

Create a resource module for VMSS Flex.    

This resource module will be used in the VMSS/LB pattern module: [[Module Proposal]: 'azurerm-avm-ptn-lbvmss' (ptn) (tf)](https://github.com/Azure/Azure-Verified-Modules/issues/29)

### Do you want to be the owner of this module?

Yes

### Module Owner's GitHub Username (handle)

terrymandin

### (Optional) Secondary Module Owner's GitHub Username (handle)

marcelkmfst

**Comment by mbilalamjad** [comment] 2023-11-04 00:03
Hi @terrymandin,

Thanks for requesting/proposing to be an AVM module owner!

We just want to confirm **you agree to the below pages** that define what module ownership means:

- [Team Definitions & RACI](https://azure.github.io/Azure-Verified-Modules/specs/shared/team-definitions)
- [Shared Specification (Bicep & Terraform)](https://azure.github.io/Azure-Verified-Modules/specs/shared)
- [Module Support](https://azure.github.io/Azure-Verified-Modules/help-support/module-support)

Any questions or clarifications needed, let us know!

If you agree, please just **reply to this issue with the exact sentence below** (as this helps with our automation 👍):

"I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER"

Thanks,

The AVM Core Team

#RR

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by terrymandin** [comment] 2023-11-06 21:10
I CONFIRM I WISH TO OWN THIS AVM MODULE AND UNDERSTAND THE REQUIREMENTS AND DEFINITION OF A MODULE OWNER

**Comment by mbilalamjad** [comment] 2023-11-09 17:32
Hi @terrymandin,

Thanks for confirming that you wish to own this AVM module and understand the related requirements and responsibilities!

We just want to ask you to double check a few important things and take the next steps before you start the development.

**Please use the following values explicitly as provided in the [module index](https://azure.github.io/Azure-Verified-Modules/indexes/) page**:

- For your module:
  - `ModuleName` - to name your module
  - `TelemetryIdPrefix` - to be used in your module's [telemetry](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr3---category-telemetry---deploymentusage-telemetry)
- For your module's repository:
  - Repository name and folder path are defined in `RepoURL`
  - Create the GitHub teams defined in the `ModuleOwnersGHTeam` and `ModuleContributorsGHTeam` columns and grant them permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr20---category-contributionsupport---github-teams-only).
    - In case of a Bicep module, **please let the AVM core team know** when you created these teams, and we'll help you with assigning the necessary permissions as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---bicep).
    - In case of a Terraform module, follow the instructions [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#grant-permissions---terraform) and assign the necessary permissions.

Grant the right level of permissions for  the AVM core team and PG teams on your GitHub repo as described [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr9---category-contributionsupport---avm--pg-teams-github-repo-permissions).

You can now start the development of this module! ✅ Happy coding! 🎉

**Please respond to this comment and request a review from the AVM core team once your module is ready to be published!** Please include a link pointing to your PR if available. 🙏

Any further questions or clarifications needed, let us know!

Thanks,

The AVM Core Team

<br>

> **NOTE**:
>
> - This Module Proposal issue **MUST remain open** until the module is fully developed, tested and published to the relevant registry. **Do NOT close** the issue before the successful publication is confirmed!
> - Once the module is fully developed, tested and published to the relevant registry, and the Module Proposal issue was closed, it **MUST remain closed**.

**Comment by terrymandin** [comment] 2023-12-09 00:58
@mbilalamjad , I have submitted a pull request to publish this module.

**Comment by mbilalamjad** [comment] 2023-12-18 23:00
Hi @terrymandin,

Thank you, Terry, for your contribution, I have reviewed the PR and made comments into it for you to consider before merging and publishing 0.1.0 to the registry.
https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/pull/10

CC: @matt-FFFFFF, @PmeshramPM, @segraef

**Comment by mbilalamjad** [comment] 2024-01-30 08:06
|Specification|Status|Comments|
|-|-|-|
|ID: PMFR1 - Category: Composition - Resource Group Creation|N/A|Only for Pattern Modules|
| ID: PMNFR1 - Category: Naming - Module Naming|N/A|Only for Pattern Modules|
| ID: PMNFR2 - Category: Composition - Use Resource Modules to Build a Pattern Module|N/A|Only for Pattern Modules|
| ID: PMNFR3 - Category: Composition - Use other Pattern Modules to Build a Pattern Module|N/A|Only for Pattern Modules|
| ID: PMNFR4 - Category: Hygiene - Missing Resource Module(s)|N/A|Only for Pattern Modules|
| ID: PMNFR5 - Category: Inputs - Parameter/Variable Naming|N/A|Only for Pattern Modules|
| ID: RMFR1 - Category: Composition - Single Resource Only|Y||
| ID: RMFR2 - Category: Composition - No Resource Wrapper Modules|Y||
| ID: RMFR3 - Category: Composition - Resource Groups|Y||
| ID: RMFR4 - Category: Composition - AVM Consistent Feature & Extension Resources Value Add|N|Verify if diagnostic_settings, private_endpoints, customer_managed_key, alerts are applicable & implemented|
| ID: RMFR5 - Category: Composition - AVM Consistent Feature & Extension Resources Value Add Interfaces/Schemas                                                                                  |N|Verify if diagnostic settings, private endpoints, customer managed key, alerts interface are applicable & implemented|
| ID: RMFR8 - Category: Composition - Dependency on child and other resources                                                                                                                    |Y|Reference to Random module only|
| ID: RMFR6 - Category: Inputs - Parameter/Variable Naming                                                                                                                                       |Y||
| ID: RMFR7 - Category: Outputs - Minimum Required Outputs                                                                                                                                       |Y||
| ID: RMNFR1 - Category: Naming - Module Naming                                                                                                                                                  |        |          |
| ID: RMNFR2 - Category: Inputs - Parameter/Variable Naming                                                                                                                                      |        |          |
| ID: RMNFR3 - Category: Composition - RP Collaboration                                                                                                                                          |        |          |
| ID: SFR1 - Category: Composition - Preview Services                                                                                                                                            |        |          |
| ID: SFR2 - Category: Composition - WAF Aligned                                                                                                                                                 |        |          |
| ID: SFR3 - Category: Telemetry - Deployment/Usage Telemetry                                                                                                                                    |        |          |
| ID: SFR4 - Category: Telemetry - Telemetry Enablement Flexibility                                                                                                                              |        |          |
| ID: SFR5 - Category: Composition - Availability Zones                                                                                                                                          |        |          |
| ID: SFR6 - Category: Composition - Data Redundancy                                                                                                                                             |        |          |
| ID: SNFR25 - Category: Composition - Resource Naming                                                                                                                                           |        |          |
| ID: SNFR1 - Category: Testing - Prescribed Tests                                                                                                                                               |        |          |
| ID: SNFR2 - Category: Testing - E2E Testing                                                                                                                                                    |        |          |
| ID: SNFR3 - Category: Testing - AVM Compliance Tests                                                                                                                                           |        |          |
| ID: SNFR4 - Category: Testing - Unit Tests                                                                                                                                                     |        |          |
| ID: SNFR5 - Category: Testing - Upgrade Tests                                                                                                                                                  |        |          |
| ID: SNFR6 - Category: Testing - Static Analysis/Linting Tests                                                                                                                                  |        |          |
| ID: SNFR7 - Category: Testing - Idempotency Tests                                                                                                                                              |        |          |
| ID: SNFR24 - Category: Testing - Testing Child, Extension & Interface Resources                                                                                                                |        |          |
| ID: SNFR8 - Category: Contribution/Support - Module Owner(s) GitHub                                                                                                                            |        |          |
| ID: SNFR20 - Category: Contribution/Support - GitHub Teams Only                                                                                                                                |        |          |
| ID: SNFR9 - Category: Contribution/Support - AVM & PG Teams GitHub Repo Permissions                                                                                                            |        |          |
| ID: SNFR10 - Category: Contribution/Support - MIT Licensing                                                                                                                                    |        |          |
| ID: SNFR11 - Category: Contribution/Support - Issues Response Times                                                                                                                            |        |          |
| ID: SNFR12 - Category: Contribution/Support - Versions Supported                                                                                                                               |        |          |
| ID: SNFR23 - Category: Contribution/Support - GitHub Repo Labels                                                                                                                               |        |          |
| ID: SNFR14 - Category: Inputs - Data Types                                                                                                                                                     |        |          |
| ID: SNFR22 - Category: Inputs - Parameters/Variables for Resource IDs                                                                                                                          |        |          |
| ID: SNFR15 - Category: Documentation - Automatic Documentation Generation                                                                                                                      |        |          |
| ID: SNFR16 - Category: Documentation - Examples/E2E                                                                                                                                            |        |          |
| ID: SNFR17 - Category: Release - Semantic Versioning                                                                                                                                           |        |          |
| ID: SNFR18 - Category: Release - Breaking Changes                                                                                                                                              |        |          |
| ID: SNFR19 - Category: Publishing - Registries Targeted                                                                                                                                        |        |          |
| ID: SNFR21 - Category: Publishing - Cross Language Collaboration                                                                                                                               |        |          |
| ID: TFFR1 - Category: Composition - Cross-Referencing Modules                                                                                                                                  |        |          |
| ID: TFFR2 - Category: Outputs - Additional Terraform Outputs                                                                                                                                   |        |          |
| ID: TFNFR1 - Category: Documentation - Descriptions                                                                                                                                            |        |          |
| ID: TFNFR2 - Category: Documentation - Module Documentation Generation                                                                                                                         |        |          |
| ID: TFNFR3 - Category: Contribution/Support - GitHub Repo Branch Protection                                                                                                                    |        |          |
| ID: TFNFR4 - Category: Composition - Code Styling - lower snake_casing                                                                                                                         |        |          |
| ID: TFNFR5 - Category: Testing - Test Tooling                                                                                                                                                  |        |          |
| ID: TFNFR6 - Category: Code Style - The Order of resource and data in the Same File                                                                                                            |        |          |
| ID: TFNFR7 - Category: Code Style - The Use of count and for_each                                                                                                                              |        |          |
| ID: TFNFR8 - Category: Code Style - Orders Within resource and data Blocks                                                                                                                     |        |          |
| ID: TFNFR9 - Category: Code Style - Order within a module block                                                                                                                                |        |          |
| ID: TFNFR10 - Category: Code Style - Values in ignore_changes passed to provider, depends_on, lifecycle blocks are not allowed to use double quotations                                        |        |          |
| ID: TFNFR11 - Category: Code Style - null comparison as creation toogle                                                                                                                        |        |          |
| ID: TFNFR12 - Category: Code Style - Optional nested object argument should use dynamic                                                                                                        |        |          |
| ID: TFNFR13 - Category: Code Style - Use coalesce or try when setting default values for nullable expressions                                                                                  |        |          |
| ID: TFFR14 - Category: Inputs - No enabled or module_depends_on variable                                                                                                                       |        |          |
| ID: TFNFR15 - Category: Code Style - Order to define variable                                                                                                                                  |        |          |
| ID: TFNFR16 - Category: Code Style - Name of a variable MUST follow rules                                                                                                                      |        |          |
| ID: TFNFR17 - Category: Code Style - Every variable MUST come with a description                                                                                                               |        |          |
| ID: TFNFR18 - Category: Code Style - Every variable MUST have an appropriate type                                                                                                              |        |          |
| ID: TFNFR19 - Category: Code Style - variable containing confidential data should be declared as sensitive = true                                                                              |        |          |
| ID: TFNFR20 - Category: Code Style - Declare nullable = false when it’s possible                                                                                                               |        |          |
| ID: TFNFR21 - Category: Code Style - MUST NOT declare nullable = true                                                                                                                          |        |          |
| ID: TFNFR22 - Category: Code Style - MUST NOT declare sensitive = false                                                                                                                        |        |          |
| ID: TFNFR23 - Category: Code Style - variable with sensitive = true MUST NOT have default value unless the default value represents turning off a feature, like default = null or default = [] |        |          |
| ID: TFNFR24 - Category: Code Style - Deal with deprecated variable                                                                                                                             |        |          |
| ID: TFNFR25 - Category: Code Style - All verified modules MUST have terraform.tf file                                                                                                          |        |          |
| ID: TFNFR26 - Category: Code Style - Provider version constraint MUST have a constraint on maximum major version                                                                               |        |          |
| ID: TFNFR27 - Category: Code Style - Declaration of a provider in the module                                                                                                                   |        |          |
| ID: TFNFR28 - Category: Code Style - output MUST be arranged alphabetically                                                                                                                    |        |          |
| ID: TFNFR29 - Category: Code Style - output contains confidential data should declare sensitive = true                                                                                         |        |          |
| ID: TFNFR30 - Category: Code Style - Dealing with Deprecated outputs                                                                                                                           |        |          |
| ID: TFNFR31 - Category: Code Style - locals.tf MUST contain only one locals block                                                                                                              |        |          |
| ID: TFNFR32 - Category: Code Style - local should be arranged alphabetically                                                                                                                   |        |          |
| ID: TFNFR33 - Category: Code Style - local should use types as precise as possible                                                                                                             |        |          |
| ID: TFNFR34 - Category: Code Style - Feature toggle MUST be used to ensure forward compatibility of versions and avoid unexpected changes caused by upgrades                                   |        |          |
| ID: TFNFR35 - Category: Code Style - Changes that might be breaking change MUST be reviewed with caution                                                                                       |        |          |
| ID: TFNFR36 - Category: Code Style - Example code MUST set prevent_deletion_if_contains_resources to false in provider block                                                                   |        |          |
| ID: TFNFR37 - Category: Code Style - Module owner MAY use tools like newres                                                                                                                    |        |          |

**Comment by mbilalamjad** [comment] 2024-01-31 07:16
@terrymandin thanks for the conversation today, have update the spec table above accordingly, once you've taken care of SNFR20 & SNFR9 than you can publish version 0.1.0 to the registry and continue to work on the rest of the specifications before releasing major version 1.

**Comment by mbilalamjad** [comment] 2024-02-08 10:15
Thank you so much @terrymandin for your contribution

Closing as module has been published to terraform registry below
https://registry.terraform.io/modules/Azure/avm-res-compute-virtualmachinescaleset/azurerm/latest

Further discussion on this module including issues & PRs to take please on its repo below
https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset

**Closed by mbilalamjad** 2024-02-08 10:15 UTC
Labels: Type: New Module Proposal :bulb:, Status: Owners Identified :metal:, Language: Terraform :globe_with_meridians:, Status: Module Available :green_circle:, Class: Resource Module :package:
